event-record-types:
  startup: {}
  shutdown: {}
  blink:
    payload-field-type:
      class: structure
      members:
        - cnt: uint8
  log_info:
    log-level: INFO
    payload-field-type:
      class: structure
      members:
        - msg: string
