native-byte-order: little-endian
$features:
  # 32 bit magic number
  magic-field-type: uint32
  # 8 bit stream ID
  data-stream-type-id-field-type: uint8
# See https://barectf.org/docs/barectf/3.0/yaml/clk-type-obj.html#props
clock-types:
  default:
    uuid: 79e49040-21b5-42d4-a873-677261696e65 # These should be unique across time domains
    description: "Default clock for the example"
    $c-type: uint32_t
    frequency: 180000000 # 180 MHz
    precision: 1
    origin-is-unix-epoch: false
data-stream-types:
  default:
    $default-clock-type-name: default
    $features:
      packet:
        # Disable packet begin/end timestamps
        beginning-timestamp-field-type: false
        end-timestamp-field-type: false
        # 16 bit size fields
        total-size-field-type: uint16
        content-size-field-type: uint16
        discarded-event-records-counter-snapshot-field-type: uint16
        # 16 bit sequence number
        sequence-number-field-type: uint16
      event-record:
        # 8 bit event IDs
        type-id-field-type: uint8
        # 32 bit timestamp
        timestamp-field-type: uint32
