[plugins]
plugins-dir = '/opt/modality/modality-reflector-plugins'

[ingest]
additional-timeline-attributes = [
    "ci_job='${GITHUB_JOB-local}'",
    "ci_commit='${GIT_SHA-local}'",
    "ci_run_id='${GITHUB_RUN_NUMBER-local}'",
]

[plugins.ingest.importers.trace-recorder.metadata]
startup-task-name = 'init'
user-event-channel = true
interaction-mode = 'ipc'
include-unknown-events = true

    [[plugins.ingest.importers.trace-recorder.metadata.user-event-fmt-arg-attr-keys]]
    channel = 'stats'
    format-string = '%s %u %u %u'
    attribute-keys = ['task', 'stack_high_water', 'task_run_time', 'total_run_time']

# Just for some plotting scripts that assume we're using imported data
[plugins.ingest.collectors.trace-recorder-rtt]
additional-timeline-attributes = [
    "trace_recorder.import.file='NA'",
]

[plugins.ingest.collectors.trace-recorder-rtt.metadata]
startup-task-name = 'init'
user-event-channel = true
interaction-mode = 'ipc'
include-unknown-events = true
attach-timeout = "10s"
attach-under-reset = true
chip = 'STM32F429ZITx'
reset = true
thumb = true
metrics = true
speed = 40000 # 40 MHz, max for st-link v2
elf-file = 'build/firmware'
breakpoint = 'main'
rtt-read-buffer-size = 1024
rtt-poll-interval = "10ms"

    [[plugins.ingest.collectors.trace-recorder-rtt.metadata.user-event-fmt-arg-attr-keys]]
    channel = 'stats'
    format-string = '%s %u %u %u'
    attribute-keys = ['task', 'stack_high_water', 'task_run_time', 'total_run_time']
