data-stream-types:
  caneth:
    $is-default: false
    $default-clock-type-name: dwt_clock
    $include:
      #- common-stream.yaml
      - test-system-stream.yaml
      - common-events.yaml
      - test-system-events.yaml
      - caneth-events.yaml
