event-record-types:
  onearg:
    payload-field-type:
      class: structure
      members:
        - one: uint8
  twoarg:
    payload-field-type:
      class: structure
      members:
        - one: uint8
        - two: uint8
